### PR TITLE
Adding TestContainers

### PR DESCRIPTION
**Pull request by jonckvanderkogel**
Hi, 
Thanks for your great samples! I learned a lot and wanted to contribute back one of the improvements I made when playing with your code. What I did is I added the TestContainers dependency and configured it so when the application is started, a Docker container with Postgres is started automatically. Once the database is ready the data initialisation will take place automatically. Also the integration tests now run without the need to start an external Postgres. Hope you like the additions I made and thanks again for your great work.

Have a nice evening, Jonck

### CODE REVIEW

**Comment by hantsy** [comment]
Hi @jonckvanderkogel , I have browsed the codes of your PR, I think it works.  But it lacks something,  my docker-compose yaml includes the scripts to create tables. 

I have also demonstrated testcontainers in  [boot-data-neo4j-rx](https://github.com/hantsy/spring-reactive-sample/blob/master/boot-data-neo4j-rx/src/test/java/com/example/demo/PostRepositoryWithTestContainersTest.java#L37-L47), it utlized the features provided in Spring Boot.

And I also added testcontainers in another sample, check here [angular-spring-reactive-sample](https://github.com/hantsy/angular-spring-reactive-sample/tree/master/server/src/test/java/com/example/demo), provided more approaches to integrate testcontainers.

I think the Spring Boot team will add more features of testcontainers integration. And Spring Data R2dbc also need more improvement in future, esp [the initial scripts issues](https://github.com/spring-projects/spring-boot/issues/20524) in Spring Boot 2.3.

**Comment by jonckvanderkogel** [comment]
Hi @hantsy,
Thanks for your feedback and explanation, I now understand how you set up your code more completely. I was only looking at your boot-data-r2dbc-postgres sub-module, I didn't look at the root, my bad. I understand that my additions do not fit in your overall strategy for setting up your project.

In case you are interested I do have a working example of how to initialise the database using Liquibase (in the r2dbc Postgres project) though you probably have that covered as well in one of your many projects.

Anyway, should you be interested in that I can change my PR to include that, otherwise I will close my PR.

Kind regards, Jonck

**Comment by hantsy** [comment]
@jonckvanderkogel  Leave it here, I maybe patch it later if I switch to R2dbc in these days.

**Comment by jonckvanderkogel** [comment]
> @jonckvanderkogel Leave it here, I maybe patch it later if I switch to R2dbc in these days.

Ok, do you mean leave the PR as is or would you like me to add the Liquibase stuff?

**Comment by hantsy** [comment]
@jonckvanderkogel Liquibase and Flyway depends on Jdbc which is conflict with R2dbc if they are in the same project.

**Comment by jonckvanderkogel** [comment]
> @jonckvanderkogel Liquibase and Flyway depends on Jdbc which is conflict with R2dbc if they are in the same project.

I was able to get it working though you are correct that it is indeed depending on jdbc. So in other words what I had to do was create a javax.sql.DataSource bean and mark it as a @LiquibaseDataSource and expose a io.r2dbc.spi.ConnectionFactory bean for the r2dbc stuff. I didn't run into any problems in my hello world application though it might lead to problems in a more real-world project, I don't know that yet. Do you have more insight into this?

Regarding the PR, I'll leave it in place, if there are other changes you are looking for or something like that please let me know. And of course feel free to close it if you want.

Kind regards, Jonck

**Comment by hantsy** [comment]
It is out of the scope of my demos whose purpose is demonstrating the features in **Spring Reactive Web**, not resolve the specific problems.

In a real-world project, you can split the Liquibase and Flyway  part into a simple separate project to maintain the database schemas. Then your codes will be simple and clean.

**Comment by jonckvanderkogel** [comment]
Yes I understand, I was just inquiring whether you wanted me to add this part in (perhaps in another PR) since you were mentioning the topic of data initialisation. It's your project, I was just seeing if I could contribute anywhere.

**Comment by hantsy** [comment]
Added testcontainers for test purpose in the [boot-data-r2dbc-postgresql](https://github.com/hantsy/spring-reactive-sample/commit/9e5f56faf84d097baa7e90bf5a1f36584947073e#diff-a93eed90eb2ebf9089085a9d30bd09fd).

Close this PR now.

**Comment by hantsy** [comment]
@jonckvanderkogel  In fact, it is a great idea now to populate data into RDBMS(till now there is no Spring official solution to this conflict) when using R2dbc, I think you can create a repository under your account to demo it and share it to the community.

**Comment by jonckvanderkogel** [comment]
> @jonckvanderkogel In fact, it is a great idea now to populate data into RDBMS(till now there is no Spring official solution to this conflict) when using R2dbc, I think you can create a repository under your account to demo it and share it to the community.

Ok, will do. Thanks again for all your great work.

**Pull request closed without merging**
